baseURL = 'https://example.org/'

title = 'dreamkidd.github.io'

languageCode = 'zh-CN'
languageName = "简体中文"
hasCJKLanguage = true

theme = 'LoveIt'

[params]
    subtitle = "Kidddddddd 的小窝"
    [params.contact]
        email = 'zhangyang911120@outlook.com'

[author]
    name = "Kidddddddd"
    email = "zhangyang911120@outlook.com"
    link = ""

[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
    pre = ""
    # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
    post = ""
    name = "文章"
    url = "/posts/"
    # 当你将鼠标悬停在此菜单链接上时, 将显示的标题
    title = ""
  [[menu.main]]
    weight = 2
    identifier = "tags"
    pre = ""
    post = ""
    name = "标签"
    url = "/tags/"
    title = ""
  [[menu.main]]
    weight = 3
    identifier = "categories"
    pre = ""
    post = ""
    name = "分类"
    url = "/categories/"
    title = ""

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
        unsafe = true
        hardWraps = true
  # 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is required for LoveIt theme(https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false

[params.carouselHomepage]
    enable = false

[outputs]
    home = ["HTML","RSS"]
